In [20]:
import torch
import plotly as pt
import matplotlib.pyplot as plt
import numpy as np

In [26]:
x = torch.randn(5, requires_grad=True) 
print(x) 

tensor([ 1.2110, -0.1416, -1.0864,  0.6353,  1.4644], requires_grad=True)


In [31]:
y = x + 2 
print(y)

z = 2 * y**2 
print(z)

z = z.mean() 
print(z) 

print(x.grad)

tensor([3.2110, 1.8584, 0.9136, 2.6353, 3.4644], grad_fn=<AddBackward0>)
tensor([20.6209,  6.9072,  1.6692, 13.8899, 24.0042], grad_fn=<MulBackward0>)
tensor(13.4183, grad_fn=<MeanBackward0>)
tensor([2.5688, 1.4867, 0.7309, 2.1083, 2.7715])
